commands:
  control:
    - name: OSC Server Connected
      endpoint: /OBSBOT/WebCam/General/Connected
      args:
        - int32
      value: any
    - name: Server Connected Reply
      endpoint: /OBSBOT/WebCam/General/ConnectedResp
      args:
        - int32
      value: 1
    - name: OSC Server Disconnected
      endpoint: /OBSBOT/WebCam/General/Disconnected
      args:
        - int32
      value: any
    - name: Select Device
      endpoint: /OBSBOT/WebCam/General/SelectDevice
      args:
        - int32
      value:
        - 0
        - 1
        - 2
        - 3
    - name: Device Sleep\Wake
      endpoint: /OBSBOT/WebCam/General/WakeSleep
      args:
        - int32
      value:
        - 0
        - 1
    - name: Gimbal Reset
      endpoint: /OBSBOT/WebCam/General/ResetGimbal
      args:
        - int32
      value: any
    - name: Zoom Set
      endpoint: /OBSBOT/WebCam/General/SetZoom
      args:
        - int32
      value: 0-100
    - name: Zoom Max
      endpoint: /OBSBOT/WebCam/General/SetZoomMax
      args:
        - int32
      value: any
    - name: Zoom Min
      endpoint: /OBSBOT/WebCam/General/SetZoomMin
      args:
        - int32
      value: any
    - name: Gimbal Set Up
      endpoint: /OBSBOT/WebCam/General/SetGimbalUp
      args:
        - int32
      value:
        - 0
        - 1
    - name: Gimbal Set Down
      endpoint: /OBSBOT/WebCam/General/SetGimbalDown
      args:
        - int32
      value:
        - 0
        - 1
    - name: Gimbal Set Left
      endpoint: /OBSBOT/WebCam/General/SetGimbalLeft
      args:
        - int32
      value:
        - 0
        - 1
    - name: Gimbal Set Right
      endpoint: /OBSBOT/WebCam/General/SetGimbalRight
      args:
        - int32
      value:
        - 0
        - 1
    - name: View Set
      endpoint: /OBSBOT/WebCam/General/SetView
      args:
        - int32
      value:
        - 0
        - 1
        - 2
    - name: AI Lock\Unlock
      endpoint: /OBSBOT/WebCam/General/ToggleAILock
      args:
        - int32
      value:
        - 0
        - 1
    - name: Select Trigger Preset Position
      endpoint: /OBSBOT/WebCam/General/TriggerPreset
      args:
        - int32
      value:
        - 0
        - 1
        - 2
    - name: Virtual Background
      endpoint: /OBSBOT/WebCam/General/SetVirtualBackground
      args:
        - int32
      value:
        - 0
        - 1
        - 2
        - 3
    - name: Auto Framing
      endpoint: /OBSBOT/WebCam/General/SetAutoFraming
      args:
        - int32
      value:
        - 0
        - 1
        - 2
    - name: Standard Mode
      endpoint: /OBSBOT/WebCam/General/SetStandardMode
      args:
        - int32
      value: any
  information:
    - name: Get Device Info
      endpoint: /OBSBOT/WebCam/General/GetDeviceInfo
      args:
        - int32
      value: any
    - name: Device Info Reply
      endpoint: /OBSBOT/WebCam/General/DeviceInfo
      args:
        - int32
        - string
        - int32
        - string
        - int32
        - string
        - int32
        - string
        - int32
        - int32
        - int32
      value: null
    - name: Get Zoom Info
      endpoint: /OBSBOT/WebCam/General/GetZoomInfo
      args:
        - int32
      value: any
    - name: Zoom Info Reply
      endpoint: /OBSBOT/WebCam/General/ZoomInfo
      args:
        - int32
        - int32
      value: ''
    - name: Get Ai Tracking Info
      endpoint: /OBSBOT/WebCam/General/GetAiTrackingInfo
      args:
        - int32
      value: any
    - name: Ai Tracking Info Reply
      endpoint: /OBSBOT/WebCam/General/AiTrackingInfo
      args:
        - int32
      value: null
    - name: Get Preset Position Info
      endpoint: /OBSBOT/WebCam/General/GetPresetPositionInfo
      args:
        - int32
      value: any
    - name: Preset Position Info Reply
      endpoint: /OBSBOT/WebCam/General/PresetPositionInfo
      args:
        - int32
        - string
        - int32
        - string
        - int32
        - string
      value: null
    - name: Get Virtual Background Info
      endpoint: /OBSBOT/WebCam/General/GetVirtualBackgroundInfo
      args:
        - int32
      value: any
    - name: Virtual Background Info Reply
      endpoint: /OBSBOT/WebCam/General/VirtualBackgroundInfo
      args:
        - int32
      value: null
    - name: Get Auto Framing Info
      endpoint: /OBSBOT/WebCam/General/GetAutoFramingInfo
      args:
        - int32
      value: any
    - name: Auto Framing Info Reply
      endpoint: /OBSBOT/WebCam/General/AutoFramingInfo
      args:
        - int32
      value: null
